# Generated by Django 5.0.4 on 2024-04-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningtoyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
